name: Routing
context:
  admissions_slab:
    teaser_collection:
      variant: 'teaser-collection--three-across'
      items: 
        - teaser: "@teaser--card-with-image.teaser"
        - teaser: "@teaser--card-with-image.teaser"
        - teaser: "@teaser--card-with-image.teaser"
  location_slab:
    teaser_collection:
      variant: 'teaser-collection--four-across'
      items:
        - teaser: "@teaser--campus-virginia.teaser"
        - teaser: "@teaser--campus-carolinas.teaser"
        - teaser: "@teaser--campus-auburn.teaser"
        - teaser: "@teaser--campus-louisiana.teaser"
  fast_facts_slab:
    fast_facts:
      items:
        - variant: virginia
          heading:
            level: 2
            headline: "23%"
          content: of VCOM students are from <a href="#" class="link--default">rural communities</a> with populations under 10,000
          icon:
            variant: icon--no-label
            glyph: ic--doctor
            label: doctor
        - variant: carolinas
          heading:
            level: 2
            headline: "#3"
          content: most affordable private medical school according to <a href="#" class= "link--default">U.S. News & World Report</a>
          icon:
            variant: icon--no-label
            glyph: ic--wallet
            label: wallet
        - variant: auburn
          heading:
            level: 2
            headline: "56%"
          content: percent of its graduates are practicing in a rural or <a href="#" class="link--default">medically underserved area</a>
          icon:
            variant: icon--no-label
            glyph: ic--bank
            label: bank
  text_slab:
    grid:
      variant: 'grid--xlarge grid--wide-gutters'
      items:
        - pattern: \@body
          pattern_context:
            body:
              variant: editorial editorial main
              items:
                - pattern: \@heading
                  pattern_context:
                    heading:
                      level: 2
                      headline: Cost & Financial Aid
                - pattern: \@p
                  pattern_context:
                    p:
                      content: Short blurb about the different locations and how you provide financial support and scholarships for prospective students who need financial assistance.
                - pattern: \@menu
                  pattern_context:
                    menu:
                      link_variant: 'link--default-list'
                      variant: 'list--bullets'
                      items:
                        - Cost of Attendance
                        - Budgeting Worksheets
                        - Types of Aid
                        - Federal Workstudy
                        - Financial Aid Handbook
                - pattern: \@button
                  pattern_context:
                    button:
                      label: Learn More
                      variant: 'button--content'
        - pattern: \@body
          pattern_context:
            body:
              variant: editorial editorial main
              items:
                - pattern: \@heading
                  pattern_context:
                    heading:
                      level: 2
                      headline: Accepted Student Info
                - pattern: \@p
                  pattern_context:
                    p:
                      content: Short blurb about the information that accepted students need to access the quick links below to provide them.
                - pattern: \@menu
                  pattern_context:
                    menu:
                      link_variant: 'link--default-list'
                      variant: 'list--bullets'
                      items:
                        - Background Check
                        - Official Transrcipt
                        - Health Immunization Forms
                        - Health Insurance
                        - Legal Status
                - pattern: \@button
                  pattern_context:
                    button:
                      label: Learn More
                      variant: 'button--content'
  feature:
    variant: feature--dark feature--flipped feature--campus virginia
    heading:
      headline: Campus Life
      level: 2
    body:
      items:
        - pattern: \@p
          pattern_context:
            p:
              content: Information about the different options that VCOM has for campus tours and what student life is like and learning more about what’s offered.
        - pattern: \@p
          pattern_context:
            p:
              content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at molestie est, vitae sollicitudin leo. Sed et feugiat lorem, sed porta ipsum. Donec lobortis ligula eget augue tempus pharetra. Aliquam erat volutpat. Quisque molestie turpis a massa rutrum. 
        - pattern: \@button
          pattern_context:
            button:
              label: Schedule a Visit
    image: "@image.image"
