name: Inset
context:
  inset:
    body:
      variant: inset__body
      items:
        - pattern: \@heading
          pattern_context:
            heading:
              level: 2
              headline: Body Content
        - pattern: \@p
          pattern_context: 
            p: "@p.p"
    alert: 
      heading:
        level: 2
        headline: Major Alert
      p:
        content: This alert style can be used for major news and evacuation alerts.
      type:
        variant: alert--major
        link:
          label: More Information
          variant: link--default
        icon: 
          glyph: ic--major_alert
          label: Major Alert
          variant: icon--big icon--no-label      

