status: wip
context:
  described_links:
    items:
      - link: Degree Programs & Certifications
        description: A post-secondary certificate is a non-degree program offered by community colleges, four-year colleges and career schools. It represents completion of a specialized training program that focuses on the development of professional skills.
      - link: Professional Volleyball @ NewCity
      - link: Anacoluthons in Literature
        description: I will have such revenges on you both, that all the world shall — I will do such things, what they are, yet I know not…
      - link: Tell You About Anastrophes, We Will
