name: Home
context:
  campus_slab:
    teaser_collection:
      items:
        - teaser: "@teaser--campus-virginia.teaser"
        - teaser: "@teaser--campus-carolinas.teaser"
        - teaser: "@teaser--campus-auburn.teaser"
        - teaser: "@teaser--campus-louisiana.teaser"
    section_intro:
      heading:
        level: 2
        headline: Where We're Located
      p:
        content: Short blurb about the different locations and how cool it is to pick from all of the campuses that are close to other universities.
  facts_slab:
    fast_facts:
      items:
        - variant: virginia
          heading:
            level: 2
            headline: "23%"
          content: of VCOM students are from <a href="#" class="link--default">rural communities</a> with populations under 10,000
          icon:
            variant: icon--no-label
            glyph: ic--doctor
            label: doctor
        - variant: carolinas
          heading:
            level: 2
            headline: "#3"
          content: most affordable private medical school according to <a href="#" class= "link--default">U.S. News & World Report</a>
          icon:
            variant: icon--no-label
            glyph: ic--wallet
            label: wallet
        - variant: auburn
          heading:
            level: 2
            headline: "56%"
          content: percent of its graduates are practicing in a rural or <a href="#" class="link--default">medically underserved area</a>
          icon:
            variant: icon--no-label
            glyph: ic--bank
            label: bank
  cards_slab:
    teaser_collection:
      variant: 'teaser-collection--three-across'
      items:
        - teaser: '@teaser--card-with-image-and-headline-only.teaser'
        - teaser: '@teaser--card-with-image-and-headline-only.teaser'
        - teaser: '@teaser--card-with-image-and-headline-only.teaser'
  feature: 
    variant: feature--dark feature--flipped feature--campus virginia
    heading:
      headline: Campus Life
      level: 2
    body:
      items:
        - pattern: \@p
          pattern_context:
            p:
              content: Information about the different options that VCOM has for campus tours and what student life is like and learning more about what’s offered.
        - pattern: \@p
          pattern_context:
            p:
              content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at molestie est, vitae sollicitudin leo. Sed et feugiat lorem, sed porta ipsum. Donec lobortis ligula eget augue tempus pharetra. Aliquam erat volutpat. Quisque molestie turpis a massa rutrum. 
        - pattern: \@button
          pattern_context:
            button:
              label: Schedule a Visit
    image: "@image.image"
  sidebar_main:
    teaser_collection:
      variant: 'teaser-collection--two-across'
      items:
        - teaser: "@teaser--news-with-image-and-headline.teaser"
        - teaser: "@teaser--news-with-image-and-headline.teaser"
        - teaser: "@teaser--news-with-image-and-headline.teaser"
        - teaser: "@teaser--news-with-image-and-headline.teaser"
  sidebar_aside:
    teaser_collection:
      variant: 'teaser-collection--full'
      items:
        - teaser: "@teaser--event-archive.teaser"
        - teaser: "@teaser--event-archive.teaser"
        - teaser: "@teaser--event-archive.teaser"
        - teaser: "@teaser--event-archive.teaser"
        - teaser: "@teaser--event-archive.teaser"