context:
  spacing: 
    - p-0
    - p-1
    - p-2
    - p-3
    - p-4
    - p-5
    - p-6
    - p-8
    - p-10
    - p-15
    - p-20
    - p-25
    - p-30
    - p-40
    - p-45
    - p-50
    - p-60
    - p-75
    - p-100