context:
  fixed:
    - xs
    - sm
    - md
    - lg
    - xl
    - 2xl
    - 3xl
    - 4xl
    - 5xl
    - 6xl
    - full
  proportional:
    - 8th
    - 4th
    - 3rd
    - half
    - 2-3rds
    - 3-4ths
    - 7-8ths